Money/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cuentas.urls')),
]

cuentas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.seguimiento, name='seguimiento'),
    path('addCategory/', views.seguimiento, name='seguimiento'),
    path('cuenta/<int:pk>/', views.detallesSeguimiento, name='detalles'),
]

cuentas/models.py
from django.db import models

# Create your models here.


class SaldoTotal(models.Model):

    saldo = models.FloatField(verbose_name='Saldo', null=True, blank=True)

    created = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')
    updated = models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')

    class Meta:
        verbose_name = 'saldo'
        verbose_name_plural = 'saldos'

    def __str__(self):
        return str(self.saldo)


class Category(models.Model):

    name = models.CharField(max_length=20, verbose_name='Categoría')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')
    updated = models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')

    class Meta:
        verbose_name = 'categoria'
        verbose_name_plural = 'categorias'

    def __str__(self) -> str:
        return self.name


class Cuenta(models.Model):

    TYPE_CHOICES = (('Ingreso', 'Ingreso'), ('Egreso', 'Egreso'))

    tipo = models.CharField(max_length=10, choices=TYPE_CHOICES, verbose_name='Tipo', default=None)
    cantidad = models.FloatField(verbose_name='Cantidad')
    categoria = models.ManyToManyField(Category, verbose_name='Categoría', related_name='categoria')
    descripcion = models.TextField(verbose_name='Descripción')
    saldo = models.ForeignKey(SaldoTotal, on_delete=models.CASCADE, verbose_name='Saldo', null=True, blank=True)

    created = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')
    updated = models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')

    class Meta:
        verbose_name = 'transacción'
        verbose_name_plural = 'transacciones'
        ordering = ['-created']

    def __str__(self):
        return str(self.cantidad)

cuentas/forms.py
from django import forms
from django.forms import widgets
from .models import Cuenta

from django.forms.models import ModelMultipleChoiceField


# class MultipleChoiceField(ModelMultipleChoiceField):
#     def label_from_instance(self, obj):
#         return "%s" % (obj.name)


class CuentaForm(forms.ModelForm):

    class Meta:
        model = Cuenta
        fields = ('tipo', 'cantidad', 'categoria', 'descripcion')
        widgets = {
            'tipo': forms.RadioSelect(attrs={'class': 'with-gap'}),
            'categoria': forms.SelectMultiple(),
            'descripcion': forms.Textarea(attrs={'style': 'font-size:12px\
                ; height:100px; border:solid black 1px;'})
        }

    # def __init__(self, *args, **kwargs):
    #     super(CuentaForm, self).__init__(*args, **kwargs)

    #     self.fields['categoria'] = MultipleChoiceField(
    #         queryset=Cuenta.objects.all(),
    #         required=True,
    #         widget=forms.SelectMultiple()
    #     )

cuentas/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from .models import Cuenta, SaldoTotal
from .forms import CuentaForm

from django import forms


def seguimiento(request, **kwargs):

    form = CuentaForm()
    transacciones = Cuenta.objects.all
    saldo = SaldoTotal.objects.get()

    if request.method == 'POST':
        form = CuentaForm(request.POST)
        if form.is_valid():
            saldo = saldoTotal(form['tipo'].value(), form['cantidad'].value())
            if not saldo:
                # raise forms.ValidationError('Transacción incorrecta: saldo menor a cero')
                return redirect('/?cero')
            else:
                form.save()

            return redirect(reverse('seguimiento'))  # Reset formulario

        else:
            print('Invalid form')

    print(request)
    print(request.path) # OJOOOOOOOOOOOOO
    if 'addCategory' in request.GET:
        print('sisas')

        # redirect('seguimiento')

    return render(request, 'cuentas/cuentas.html', {'transacciones': transacciones, 'form': form, 'saldo': saldo})


def detallesSeguimiento(request, pk):

    cuenta = get_object_or_404(Cuenta, pk=pk)

    if request.method == 'POST':
        form = CuentaForm(request.POST, instance=cuenta)
        if form.is_valid():

            if 'botonEliminar' in request.POST:
                if cuenta.tipo == 'Ingreso':
                    saldo = saldoTotal('Egreso', cuenta.cantidad)
                else:
                    saldo = saldoTotal('Ingreso', cuenta.cantidad)
                cuenta.delete()
            else:
                operacion, valor = verificarTransaccion(cuenta.tipo, form['tipo'].value(), cuenta.cantidad, form['cantidad'].value())
                if operacion is not False:
                    saldo = saldoTotal(operacion, valor)
                form.save()

        return redirect(reverse('seguimiento'))

    else:
        form = CuentaForm(instance=cuenta)

    return render(request, 'cuentas/cuentas_info.html', {'cuenta': cuenta, 'form': form})


def verificarTransaccion(cuentaTipo, formTipo, cuentaCantidad, formCantidad):

    print(cuentaTipo)
    print(formTipo)

    # El tipo de transacción no cambia
    if cuentaTipo == formTipo:
        # El nuevo valor es mayor al anterior
        if cuentaCantidad < float(formCantidad):
            operacion = 'Ingreso'
            valor = float(formCantidad) - cuentaCantidad
        # El nuevo valor es menor al anterior
        elif cuentaCantidad > float(formCantidad):
            operacion = 'Egreso'
            valor = cuentaCantidad - float(formCantidad)
        # El valor no cambia
        else:
            operacion = False
            valor = False

    # Transacción pasa de Ingreso a Egreso
    elif cuentaTipo == 'Ingreso' and formTipo == 'Egreso':
        operacion = 'Egreso'
        valor = cuentaCantidad + float(formCantidad)

    # Transacción pasa de Egreso a Ingreso
    elif cuentaTipo == 'Egreso' and formTipo == 'Ingreso':
        operacion = 'Ingreso'
        valor = cuentaCantidad + float(formCantidad)

    return operacion, valor


def saldoTotal(operacion, valor):

    saldo = SaldoTotal.objects.get()

    if operacion == 'Ingreso':
        saldo.saldo += float(valor)
    else:
        saldo.saldo -= float(valor)

    if saldo.saldo >= 0:
        saldo.save()
        return saldo
    else:
        return None

cuentas/templates/cuentas/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title> {% block title %}{% endblock %} | Money </title>
    
    <!--Librería materializecss-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static '../static/css/styles.css' %}">
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>

    <h3>Economía</h3>

    {% block content %}

    {% endblock %}

    <!--Librería materializecss-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src='static/js/scripts.js'></script>
    
</body>
</html>

cuentas/templates/cuentas/cuentas.html
{% extends 'cuentas/base.html' %}

{% block title %} Dinerosss {% endblock %}

{% block content %}

AGREGAR CATEGORÍA
LIMITAR EL NÚMERO DE TRANSACCIONES

<div class="row">

    <div class="col s12 l4">
        <div class="col s8 l11 offset-s2 offset-l1">
            
            <form method="POST" id="transactionForm">{% csrf_token %}

                <div class="formField">
                    <p>
                        <span id="tipo">{{form.tipo.label}}:</span>

                        {% for radio in form.tipo %}
                            <label for="{{radio.id_for_label}}" id="ingreso">
                                {{radio.tag}}
                            <span class="radio">{{radio.choice_label}}</span>
                            </label>
                        {% endfor %}

                    </p>
                </div>

                <div class="input-field">
                    <label>Monto</label>
                    {{form.cantidad}}
                </div>

                <div class="formField" id="ptm">
                    <div class="col s6 l6">

                        <span>Categoría</span>
                        
                    
                        <select multiple required size='5' style="height:100%"
                        name="categoria" id="id_categoria" class="browser-default">

                            {% for categoria in form.categoria %}
                                {{categoria.tag}}
                            {% endfor %}

                        </select>

                    </div>

                    <div class="col s5 l5">

                        <div>
                            <label>
                                <input id=radioCategory class="with-gap" type="radio" />
                                <span>Agregar categoría</span>
                            </label>
                            
                            <div class="input-field">
                                <label id='categoryLabel' for="addCategory" style="display:inline">Ingrese Categoría</label>
                                <input id="categoryInput" type="text" class="validate">

                                <p>
                                    <a href="" id='addCategory' style="visibility:visible">Agregar</a>
                                </p>

                            </div>
            
                        </div>

                    </div>
                    
                </div>

                <div class="input-field">
                    <label id="labelDescription">Descripción</label>
                    {{form.descripcion}}
                </div>


                <div class="post" id="divBoton">
                    <!-- <button onclick="location.href='{% url "seguimiento" %}"\ -->
                    <button
                    class="btn waves-effect waves-light" id="botoAgregar" type="submit">Agregar
                        <i class="material-icons right">monetization_on</i>
                    </button>
                </div>

            </form>

            <div id='totalLabel'>
                <label style="font-size: 20px; color: black;" for="">TOTAL:</label>
                <label style="font-size: 20px; color: black; padding-left: 10px;" for="">$&nbsp;{{saldo.saldo}}</label>
            </div>

            {% if 'cero' in request.GET %}
            <p style="text-align: center">Dinero insuficiente para esta transacción</p>
            {% endif %}

        </div>
    </div>

    <div class="col s12 l5 offset-l1" id="tableDiv">
        <table id=transactionTable> <!--class='responsive-table'-->
            <caption><h6>CAMINO A LA RIQUEZA</h6></caption>
            <thead>
                <tr>
                    <th>
                        Tipo
                    </th>
                    <th>
                        Cantidad
                    </th>
                    <th>
                        Categoría
                    </th>
                    <th>
                        Descripción
                    </th>
                    <th>
                        Fecha
                    </th>
                </tr>
            </thead>

            <tbody>

                {% for transaccion in transacciones %}
                    <tr>
                        <td>
                            <u><a href="{% url 'detalles' transaccion.id %}" style="color: black;">{{transaccion.tipo}}</a></u>
                        </td>
                        <td>
                            {{transaccion.cantidad}}
                        </td>
                        <td>
                            {% for categoria in transaccion.categoria.all %}
                                {{categoria}}{% if not forloop.last %},{% endif %}
                            {% endfor %}
                        </td>
                        <td>
                            {{transaccion.descripcion}}
                        </td>
                        <td>
                            {{transaccion.created}}
                        </td>
                    </tr>
                {% endfor %}
            
            </tbody>
        </table>
    </div>

</div>

{% endblock %}

cuentas/templates/cuentas/cuentas_info.html
{% extends 'cuentas/base.html' %}

{% block title %} Detalles {% endblock %}

{% block content %}

<div class="row">

    <div class="col l5 s12 offset-l1">

        <table id=transactionTable> <!--class='responsive-table'-->

            <thead>
                <tr>
                    <th>
                        Tipo
                    </th>
                    <th>
                        Cantidad
                    </th>
                    <th>
                        Categoría
                    </th>
                    <th>
                        Descripción
                    </th>
                    <th>
                        Fecha
                    </th>
                </tr>
            </thead>

            <tbody>

                    <tr>
                        <td>
                            {{cuenta.tipo}}
                        </td>
                        <td>
                            {{cuenta.cantidad}}
                        </td>
                        <td>
                            {% for categoria in cuenta.categoria.all %}
                                {{categoria}}{% if not forloop.last %},{% endif %}
                            {% endfor %}
                        </td>
                        <td>
                            {{cuenta.descripcion}}
                        </td>
                        <td>
                            {{cuenta.created}}
                        </td>
                    </tr>

            </tbody>
        </table>
        <br>
    </div>

    <div class="col l4 s12">
        <div class="col s8 l11 offset-s2 offset-l1">

            <form method="POST" id="transactionForm">{% csrf_token %}

                <div class="formField">
                    <p>
                        <span id="tipo">{{form.tipo.label}}:</span>

                        {% for radio in form.tipo %}
                            <label for="{{radio.id_for_label}}" id="ingreso">
                                {{radio.tag}}
                            <span class="radio">{{radio.choice_label}}</span>
                            </label>
                        {% endfor %}

                    </p>
                </div>

                <div class="input-field">
                    <label for="transactionAmount">Monto</label>
                    {{form.cantidad}}
                </div>

                <div class="formField">

                    <span>Categoría</span>


                    <select multiple required size='5' style="height:100%"
                    name="categoria" id="id_categoria" class="browser-default">

                        {% for categoria in form.categoria %}
                            {{categoria.tag}}
                        {% endfor %}

                    </select>
                </div>

                <div class="input-field">
                    <label id="labelDescription" for="transactionalDescription">Descripción</label>
                    {{form.descripcion}}
                </div>

                <div class="post" id="divBoton">
                    <!-- <button onclick="location.href='{% url "seguimiento" %}"\ -->
                    <button
                    class="btn waves-effect waves-light" id="botonAgregar" type="submit">Editar
                        <i class="material-icons right">monetization_on</i>
                    </button>
                    <button  type="submit"
                    class="btn waves-effect waves-light" name="botonEliminar" id="botonEliminar">Eliminar
                        <i class="material-icons right">delete_forever</i>
                    </button>
                </div>

            </form>

        </div>
    </div>
</div>

{% endblock %}